### ISSUE TITLE
Please add description of what it is actually for

### ISSUE THREAD

**Issue by yurivict** [djc/rnc2rng#13]
I have created the FreeBSD port for it, but I couldn't find any meaningful description beyond of the vague one line that is on the top of the GitHub page.

**Comment by djc** [comment]
I would have thought that it was pretty obvious to people who actually needed it. Why did you create a port if you don't understand what it is for? :) 086abceb986a8b044e1a7b1b0978c981f569744c attempts to clarify the README, let me know if that helps.

**Comment by yurivict** [comment]
> Why did you create a port if you don't understand what it is for? :)

Because it was listed as a dependency of some other package. -)
