### ISSUE TITLE
Support for Py 3.7 and 3.8

### ISSUE THREAD

**Issue by eamanu** [djc/rnc2rng#22]
Hello, 

I am working on rnc2rng packaing [0]. On [1] the seems that the plan is don't have
support for python3.7 on that moment. Looking on the travis failure [2]
seems like the problems is from the Travis and not from the rnc2rng.

I fork the repository and run the tests for py3.7 and py3.8 and run successfully [3]
https://travis-ci.org/github/eamanu/rnc2rng/builds/671426809
I recommend you add the support to python 3.7 and 3.8 to be compatible with the
current systems, please.

[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865666
[1] https://github.com/djc/rnc2rng/commit/2b2c3c7c7f6a59055e68aea53769028609b469e9
[2]  https://travis-ci.org/github/djc/rnc2rng/jobs/407200803?utm_medium=notification&utm_source=github_status

**Comment by djc** [comment]
Hi @eamanu, thanks for packaging rnc2rng! I've just released 2.6.2 which contains your changes as well as some other minor improvements.
