### ISSUE TITLE
Regression: "Allow annotations ..." started to cause failures for citeproc-py

### ISSUE THREAD

**Issue by yarikoptic** [djc/rnc2rng#28]
I believe (through manual bisection) that it was d1bd9b26f024d66d2fc9cbda69a2448af84d86cd (" Allow annotations on top-level body") included in 2.6.2 which introduced a regression which causes citeproc-py failures (https://github.com/brechtm/citeproc-py/issues/94).

edit: this is the rnc file - -https://github.com/citation-style-language/schema/blob/e295d632a7548470457761d63cb9dad561afa84d/csl.rnc

**Comment by djc** [comment]
Could you provide a minimal reproduction, please?

**Comment by yarikoptic** [comment]
Let me shine my ignorance in the subject ;)

if before
```
namespace dc = "http://purl.org/dc/elements/1.1/"

dc:title [ "Citation Style Language" ]
```
worked before and produced
```
$> rnc2rng min.rnc
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0"
         xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:title>Citation Style Language</dc:title>
</grammar>
```
now rnc2rng requires `start` to be present before defining any terms (e.g. `dc:title`).
 
In [csl.rnc](https://github.com/citation-style-language/schema/blob/e295d632a7548470457761d63cb9dad561afa84d/csl.rnc) we have start [further down within `div`](https://github.com/citation-style-language/schema/blob/e295d632a7548470457761d63cb9dad561afa84d/csl.rnc#L53)

I could move it up, but that moves it then also in produced .rng and I am not sure if that does not matter or if desired:
```
$> diff -Naur /tmp/2.6.1 /tmp/2.6.2
--- /tmp/2.6.1	2020-04-06 16:10:02.996929689 -0400
+++ /tmp/2.6.2	2020-04-06 16:13:10.266599018 -0400
@@ -8,6 +8,13 @@
          xmlns:xhtml="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
+  <start>
+    <choice>
+      <ref name="independent-style.style"/>
+      <ref name="dependent-style.style"/>
+      <ref name="locale-file.locale"/>
+    </choice>
+  </start>
   <dc:title>Citation Style Language</dc:title>
   <dc:creator>Bruce D&#x27;Arcus</dc:creator>
   <dc:creator>Simon Kornblith</dc:creator>
@@ -373,13 +380,6 @@
     <a:documentation>
       <xhtml:h2>cs:style and cs:locale - Root Elements</xhtml:h2>
     </a:documentation>
-    <start>
-      <choice>
-        <ref name="independent-style.style"/>
-        <ref name="dependent-style.style"/>
-        <ref name="locale-file.locale"/>
-      </choice>
-    </start>
     <define name="independent-style.style">
       <element>
         <name ns="http://purl.org/net/xbiblio/csl">style</name>
```
I do not know if that is CSL format requirement to have start high up in the definition?

**Comment by yarikoptic** [comment]
any further information I could provide to facilitate a fix?
