### ISSUE TITLE
Update Python version

### ISSUE THREAD

**Issue by ulm** [djc/rnc2rng#48]
`setup.py` and Github CI list Python versions 3.7, 3.8 and 3.9. The latter will reach end-of-life status next year. So, could these be updated?

Tests appear to succeed with Python 3.12: https://bugs.gentoo.org/929367#c1

**Comment by jombr** [comment]
Yes absolutely. I just haven't gotten around to it.

I assume the preference is 3.8, 3.9, 3.10, 3.11, 3.12?
 - with 3.8 reaching EOL in October this year (2024-10)
 - Adding 3.13 would be a good thing to do around the same time (First release 2024-10-01)

Based on https://devguide.python.org/versions/#supported-versions.

If this seems right to you I'll update it (in the setup.py and the ci.yml workflow)
